package wizard

import (
	"fmt"
	"os"
	"path/filepath"

	"go.yaml.in/yaml/v3"

	"github.com/heinrichb/steamgifts-bot/internal/config"
)

// saveConfigYAML mirrors cli.saveConfig — duplicated here so the wizard
// package doesn't import the cli package (which would create a cycle).
func saveConfigYAML(cfg *config.Config, path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("save: mkdir: %w", err)
	}
	out, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("save: marshal: %w", err)
	}
	header := []byte("# steamgifts-bot config — generated by `setup`. Re-run setup any time to edit.\n" +
		"# This file contains session cookies; keep it private.\n\n")
	return os.WriteFile(path, append(header, out...), 0o600)
}
