package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/viper"
	"go.yaml.in/yaml/v3"

	"github.com/heinrichb/steamgifts-bot/internal/config"
)

// configCandidates returns the search paths checked when --config is not set.
// First match wins. We look beside the binary first so a Windows user who
// double-clicks the .exe and runs the wizard ends up with config.yml right
// next to it (zero-friction discovery).
func configCandidates() []string {
	var paths []string
	if exe, err := os.Executable(); err == nil {
		paths = append(paths, filepath.Join(filepath.Dir(exe), "config.yml"))
	}
	if cwd, err := os.Getwd(); err == nil {
		paths = append(paths, filepath.Join(cwd, "config.yml"))
	}
	if dir, err := os.UserConfigDir(); err == nil {
		paths = append(paths, filepath.Join(dir, "steamgifts-bot", "config.yml"))
	}
	return paths
}

// findConfig returns the first existing path from configCandidates, or "".
func findConfig() string {
	for _, p := range configCandidates() {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

// defaultSavePath is where the wizard writes a freshly-created config.
func defaultSavePath() string {
	if exe, err := os.Executable(); err == nil {
		return filepath.Join(filepath.Dir(exe), "config.yml")
	}
	if dir, err := os.UserConfigDir(); err == nil {
		return filepath.Join(dir, "steamgifts-bot", "config.yml")
	}
	return "config.yml"
}

// loadConfig reads the YAML config from `path` (or auto-discovered location),
// merges in environment-variable overrides, and returns the validated config.
//
// Validation is the caller's responsibility — `setup` and `check` want to
// load partial/empty configs without failing here.
func loadConfig(path string) (*config.Config, string, error) {
	if path == "" {
		path = findConfig()
	}
	if path == "" {
		return nil, "", os.ErrNotExist
	}

	v := viper.New()
	v.SetConfigFile(path)
	v.SetConfigType("yaml")
	v.SetEnvPrefix("STEAMGIFTS")
	v.SetEnvKeyReplacer(strings.NewReplacer(".", "_"))
	v.AutomaticEnv()

	if err := v.ReadInConfig(); err != nil {
		return nil, path, fmt.Errorf("read %s: %w", path, err)
	}

	cfg := config.Defaults()
	if err := v.Unmarshal(&cfg); err != nil {
		return nil, path, fmt.Errorf("decode %s: %w", path, err)
	}
	return &cfg, path, nil
}

// saveConfig writes the config to disk as YAML, creating parent directories
// as needed and setting strict permissions (the file holds session cookies).
func saveConfig(cfg *config.Config, path string) error {
	if path == "" {
		return errors.New("save: path required")
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("save: mkdir: %w", err)
	}
	out, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("save: marshal: %w", err)
	}
	header := []byte("# steamgifts-bot config — generated by `setup`. Re-run setup any time to edit.\n" +
		"# This file contains session cookies; keep it private.\n\n")
	if err := os.WriteFile(path, append(header, out...), 0o600); err != nil {
		return fmt.Errorf("save: write: %w", err)
	}
	return nil
}
